# Numpy -  multidimensional data arrays

BitTiger DS501

## Introduction

The `numpy` package (module) is used in almost all numerical computation using Python. 

It is a package that provide high-performance vector, matrix and higher-dimensional data structures for Python. 

It is implemented in C and Fortran so when calculations are vectorized (formulated with vectors and matrices), performance is very good. 

In [1]:
import numpy as np

## Creating `numpy` arrays

In the `numpy` package the terminology used for vectors, matrices and higher-dimensional data sets is *array*. 

There are a number of ways to initialize new numpy arrays, for example from

* a Python *list* or *tuples*
* using functions that are dedicated to generating numpy arrays, such as `arange`, `linspace`, etc.
* reading data from files

### From lists

For example, to create new vector and matrix arrays from Python lists we can use the `numpy.array` function.

In [2]:
# a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [3]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4]])
M

array([[1, 2],
       [3, 4]])

The `v` and `M` objects are both of the type `ndarray` that the `numpy` module provides.

In [4]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

The difference between the `v` and `M` arrays is only their shapes. We can get information about the shape of an array by using the `ndarray.shape` property.

In [5]:
v.shape

(4,)

In [6]:
M.shape

(2, 2)

The number of elements in the array is available through the `ndarray.size` property:

In [7]:
M.size

4

Equivalently, we could use the function `numpy.shape` and `numpy.size`

In [8]:
np.shape(M)

(2, 2)

In [9]:
np.size(M)

4

So far the `numpy.ndarray` looks very much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type? 

There are several reasons:

* Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. Implementing such functions for Python lists would not be very efficient because of the dynamic typing.
* Numpy arrays are **statically typed** and **homogeneous**. The type of the elements is determined when the array is created.
* Numpy arrays are memory efficient.
* Because of the static typing, fast implementation of mathematical functions such as multiplication and addition of `numpy` arrays can be implemented in a compiled language (C and Fortran is used).

Using the `dtype` (data type) property of an `ndarray`, we can see what type the data of an array has:

In [10]:
M.dtype

dtype('int64')

We get an error if we try to assign a value of the wrong type to an element in a numpy array:

In [11]:
M[0,0] = "hello"

ValueError: invalid literal for int() with base 10: 'hello'

If we want, we can explicitly define the type of the array data when we create it, using the `dtype` keyword argument: 

In [12]:
M = np.array([[1, 2], [3, 4]], dtype=int)
M

array([[1, 2],
       [3, 4]])

In [13]:
M = np.array([[1, 2], [3, 4]], dtype=float)
M

array([[ 1.,  2.],
       [ 3.,  4.]])

Common data types that can be used with `dtype` are: `int`, `float`, `complex`, `bool`, `object`, etc.

We can also explicitly define the bit size of the data types, for example: `int64`, `int16`, `float128`, `complex128`.

#### Type casting
Since Numpy arrays are *statically typed*, the type of an array does not change once created. But we can explicitly cast an array of some type to another using the `astype` functions (see also the similar `asarray` function). This always create a new array of new type:

In [14]:
M.dtype

dtype('float64')

In [15]:
M2 = M.astype(int)

M2

array([[1, 2],
       [3, 4]])

In [16]:
M2.dtype

dtype('int64')

In [17]:
M3 = M.astype(bool)

M3

array([[ True,  True],
       [ True,  True]], dtype=bool)

### Using array-generating functions

For larger arrays it is impractical to initialize the data manually, using explicit python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

#### arange

In [18]:
# create a range
x = np.arange(0, 10, 1) # arguments: start, stop, stepsize
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x = np.arange(-1, 1, 0.1)
x

array([ -1.00000000e+00,  -9.00000000e-01,  -8.00000000e-01,
        -7.00000000e-01,  -6.00000000e-01,  -5.00000000e-01,
        -4.00000000e-01,  -3.00000000e-01,  -2.00000000e-01,
        -1.00000000e-01,  -2.22044605e-16,   1.00000000e-01,
         2.00000000e-01,   3.00000000e-01,   4.00000000e-01,
         5.00000000e-01,   6.00000000e-01,   7.00000000e-01,
         8.00000000e-01,   9.00000000e-01])

#### linspace and logspace

In [20]:
# using linspace, both end points ARE included
np.linspace(0, 10, 25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [21]:
np.logspace(0, 10, 10, base=np.e)

array([  1.00000000e+00,   3.03773178e+00,   9.22781435e+00,
         2.80316249e+01,   8.51525577e+01,   2.58670631e+02,
         7.85771994e+02,   2.38696456e+03,   7.25095809e+03,
         2.20264658e+04])

#### random data

In [22]:
# uniform random numbers in [0,1]
np.random.rand(5,5)

array([[ 0.74662749,  0.37296158,  0.08512613,  0.66334415,  0.43749676],
       [ 0.6149436 ,  0.55037203,  0.43945216,  0.91773815,  0.00538092],
       [ 0.60044943,  0.29653064,  0.84630647,  0.64749745,  0.37290613],
       [ 0.24921367,  0.21280261,  0.48764264,  0.86513719,  0.06093594],
       [ 0.51036509,  0.3166254 ,  0.35397053,  0.36996456,  0.96133875]])

In [23]:
# standard normal distributed random numbers
np.random.randn(5,5)

array([[ 0.21048157, -0.92910507, -0.31972399,  1.44898736,  0.13110283],
       [-0.91199129,  1.00879753, -0.41388804,  0.03901736,  3.19305738],
       [ 1.17336197,  0.87911314, -0.96315606,  0.96945986, -0.78833505],
       [-0.42266028, -0.52371879, -0.92906158, -0.56729055,  0.43622793],
       [-1.37487532,  0.4381285 , -0.1296802 , -0.80852706,  0.10480321]])

In [24]:
# random integers
np.random.randint(0, 9, 5) # [low , high), size

array([0, 1, 5, 8, 1])

#### diag

In [25]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [26]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=-1) 

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0]])

#### zeros and ones

In [27]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [28]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## Manipulating arrays

### Indexing

We can index elements in an array using square brackets and indices:

In [29]:
v = np.array([1, 2, 3, 4])

# v is a vector, and has only one dimension, taking one index
v[0]

1

In [30]:
M = np.array([[1, 2], [3, 4]])

# M is a matrix, or a 2 dimensional array, taking two indices 
M[1,1]

4

If we omit an index of a multidimensional array it returns the whole row (or, in general, a N-1 dimensional array) 

In [31]:
M.shape

(2, 2)

In [32]:
M[1]

array([3, 4])

The same thing can be achieved with using `:` instead of an index: 

In [33]:
M[1,:] # row 1

array([3, 4])

In [34]:
M[:,1] # column 1

array([2, 4])

We can assign new values to elements in an array using indexing:

In [35]:
M[0,0] = 0

In [36]:
M

array([[0, 2],
       [3, 4]])

In [37]:
# also works for rows and columns
M[1,:] = 10
M

array([[ 0,  2],
       [10, 10]])

In [38]:
M[:,1] = -10
M

array([[  0, -10],
       [ 10, -10]])

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:stepsize]` to extract part of an array:

In [39]:
A = np.array([1, 2, 3, 4, 5])
A

array([1, 2, 3, 4, 5])

In [40]:
A[1:3]

array([2, 3])

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [41]:
A[1:3] = [-2, -3]
A

array([ 1, -2, -3,  4,  5])

We can omit any of the three parameters in `M[lower:upper:stepsize]`:

In [42]:
A[::] # lower, upper, stepsize all take the default values

array([ 1, -2, -3,  4,  5])

In [43]:
A[::-1] # stepsize is 2, lower and upper defaults to the beginning and end of the array

array([ 5,  4, -3, -2,  1])

In [44]:
A[:3] # first three elements

array([ 1, -2, -3])

In [45]:
A[3:] # elements from index 3

array([4, 5])

Negative indices counts from the end of the array (positive index from the begining):

In [46]:
A = np.array([1, 2, 3, 4, 5])

In [47]:
A[-1] # the last element in the array

5

In [48]:
A[-3:] # the last three elements

array([3, 4, 5])

Index slicing works exactly the same way for multidimensional arrays:

In [49]:
A = np.array([[ 0,  1,  2,  3,  4],
              [10, 11, 12, 13, 14],
              [20, 21, 22, 23, 24],
              [30, 31, 32, 33, 34],
              [40, 41, 42, 43, 44]])

A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [50]:
# a block from the original array
A[1:4, 1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [51]:
# strides
A[::2, ::2]

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

### Index Array

Numpy arrays may be indexed with other arrays (or any other sequence-like object that can be converted to an array, such as lists)

In [52]:
A = np.array([[ 0,  1,  2,  3,  4],
              [10, 11, 12, 13, 14],
              [20, 21, 22, 23, 24],
              [30, 31, 32, 33, 34],
              [40, 41, 42, 43, 44]])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [53]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [54]:
row_indices = np.array([1, 2, 3])
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [55]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

array([11, 22, 34])

### Boolean or “mask” index arrays

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [56]:
B = np.array([0, 1, 2, 3, 4])
B

array([0, 1, 2, 3, 4])

In [57]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [58]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [59]:
x = np.arange(0, 10, 0.5)
x

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [60]:
x < 7.5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False], dtype=bool)

In [61]:
5 < x

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

In [62]:
mask = (5 < x) * (x < 7.5)

mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False], dtype=bool)

In [63]:
x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

## Functions for extracting data from arrays and creating arrays

### where

The index mask can be converted to position index using the `where` function

In [64]:
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False], dtype=bool)

In [65]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [66]:
x[indices] # this indexing is equivalent to the fancy indexing x[mask]

array([ 5.5,  6. ,  6.5,  7. ])

### take

The `take` function is similar to fancy indexing described above:

In [67]:
v2 = np.arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [68]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

array([-2, -1,  0])

In [69]:
row_indices = [1, 3, 5]
v2[row_indices] # fancy indexing

array([-2,  0,  2])

In [70]:
v2.take(row_indices)

array([-2,  0,  2])

But `take` also works on lists and other objects:

In [71]:
np.take([-3, -2, -1,  0,  1,  2], row_indices)

array([-2,  0,  2])

### choose

Constructs an array by picking elements from several arrays:

In [72]:
which = [1, 0, 1, 0]
choices = [[-2,-2,-2,-2], [5,5,5,5]]

np.choose(which, choices)

array([ 5, -2,  5, -2])

### diag

With the diag function we can also extract the diagonal and subdiagonals of an array:

In [73]:
np.diag(A)

array([ 0, 11, 22, 33, 44])

In [74]:
np.diag(A, -1)

array([10, 21, 32, 43])

## Linear algebra

Vectorizing code is the key to writing efficient numerical calculation with Python/Numpy. That means that as much as possible of a program should be formulated in terms of matrix and vector operations, like matrix-matrix multiplication.

### Scalar-array operations

We can use the usual arithmetic operators to multiply, add, subtract, and divide arrays with scalar numbers.

In [75]:
v1 = np.arange(0, 5)

In [76]:
v1

array([0, 1, 2, 3, 4])

In [77]:
v1 * 2

array([0, 2, 4, 6, 8])

In [78]:
v1 + 2

array([2, 3, 4, 5, 6])

In [79]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [80]:
A * 2

array([[ 0,  2,  4,  6,  8],
       [20, 22, 24, 26, 28],
       [40, 42, 44, 46, 48],
       [60, 62, 64, 66, 68],
       [80, 82, 84, 86, 88]])

In [81]:
A + 2

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16],
       [22, 23, 24, 25, 26],
       [32, 33, 34, 35, 36],
       [42, 43, 44, 45, 46]])

### Element-wise array-array operations

When we add, subtract, multiply and divide arrays with each other, the **default** behaviour is **element-wise** operations:

In [82]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [83]:
A * A # element-wise multiplication

array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [84]:
v1 * v1

array([ 0,  1,  4,  9, 16])

If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row:

In [85]:
A.shape, v1.shape

((5, 5), (5,))

In [86]:
A * v1

array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

### Matrix algebra

What about matrix mutiplication? There are two ways. We can either use the `dot` function, which applies a matrix-matrix, matrix-vector, or inner vector multiplication to its two arguments: 

In [87]:
np.dot(A, A)

array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [88]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [89]:
np.dot(v1, v1)

30

Alternatively, we can cast the array objects to the type `matrix`. This changes the behavior of the standard arithmetic operators `+, -, *` to use matrix algebra.

In [90]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector

In [91]:
v

matrix([[0],
        [1],
        [2],
        [3],
        [4]])

In [92]:
v.shape

(5, 1)

In [93]:
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [94]:
M * v

matrix([[ 30],
        [130],
        [230],
        [330],
        [430]])

In [95]:
# inner product
v.T * v

matrix([[30]])

In [96]:
# with matrix objects, standard matrix algebra applies
v + M * v

matrix([[ 30],
        [131],
        [232],
        [333],
        [434]])

If we try to add, subtract or multiply objects with incomplatible shapes we get an error:

In [97]:
v = np.matrix([1, 2, 3, 4, 5, 6]).T

In [98]:
M.shape, v.shape

((5, 5), (6, 1))

In [99]:
# M * v

See also the related functions: `inner`, `outer`, `cross`, `kron`, `tensordot`. Try for example `help(kron)`.

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

In [100]:
data = np.random.RandomState(seed=1).randint(1, 30, 30).reshape(5,6)
data

array([[ 6, 12, 13,  9, 10, 12],
       [ 6, 16,  1, 17,  2, 13],
       [ 8, 14, 29,  7, 26, 19],
       [21,  6, 19, 21, 12, 29],
       [11, 29, 15, 19,  5, 24]])

In [101]:
np.shape(data)

(5, 6)

#### mean

In [102]:
# the temperature data is in column 3
np.mean(data[:,3])

14.6

#### standard deviations and variance

In [103]:
np.std(data[:,3]), np.var(data[:,3])

(5.5713553108736482, 31.040000000000003)

#### min and max

In [104]:
# lowest daily average temperature
data[:,3].min()

7

In [105]:
# highest daily average temperature
data[:,3].max()

21

#### sum, prod, and trace

In [106]:
d = np.arange(0, 10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
# sum up all elements
np.sum(d)

45

In [108]:
# product of all elements
np.prod(d+1)

3628800

In [109]:
# cummulative sum
np.cumsum(d)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [110]:
# cummulative product
np.cumprod(d + 1)

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [111]:
# same as: diag(A).sum()
np.trace(A)

110

### Calculations with higher-dimensional data

When functions such as `min`, `max`, etc. are applied to a multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [112]:
m = np.random.rand(3,3)
m

array([[ 0.97409698,  0.5699438 ,  0.58751929],
       [ 0.10317714,  0.11942444,  0.91495292],
       [ 0.97851256,  0.23497365,  0.70091487]])

In [113]:
# global max
m.max()

0.97851255599955589

In [114]:
# max in each column
m.max(axis=0)

array([ 0.97851256,  0.5699438 ,  0.91495292])

In [115]:
# max in each row
m.max(axis=1)

array([ 0.97409698,  0.91495292,  0.97851256])

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [116]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [117]:
n, m = A.shape

In [118]:
B = A.reshape((1,n*m))
B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [119]:
B[0,0:5] = 5 # modify the array
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
        32, 33, 34, 40, 41, 42, 43, 44]])

In [120]:
A # and the original variable is also changed. B is only a different view of the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function create a copy of the data.

In [121]:
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [122]:
B[0:5] = 10
B

array([10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [123]:
A # now A has not changed, because B's data is a copy of A's, not refering to the same data

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

### Adding a new dimension: newaxis

With `newaxis`, we can insert new dimensions in an array, for example converting a vector to a column or row matrix:

In [124]:
v = np.array([1,2,3])

In [125]:
v.shape

(3,)

In [126]:
# make a column matrix of the vector v
v[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [127]:
# column matrix
v[:,np.newaxis].shape

(3, 1)

In [128]:
# row matrix
v[np.newaxis,:].shape

(1, 3)

## Copy and "deep copy"

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [129]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [130]:
# now B is referring to the same array data as A 
B = A 

In [131]:
# changing B affects A
B[0,0] = 10

B

array([[10,  2],
       [ 3,  4]])

In [132]:
A

array([[10,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to do a so-called "deep copy" using the function `copy`:

In [133]:
B = np.copy(A)

In [134]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

array([[-5,  2],
       [ 3,  4]])

In [135]:
A

array([[10,  2],
       [ 3,  4]])

## Iterating over array elements

In [136]:
v = np.array([1, 2, 3, 4])

for element in v:
    print(element)

1
2
3
4


In [137]:
M = np.array([[1, 2], [3, 4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

row [1 2]
1
2
row [3 4]
3
4


When we need to iterate over each element of an array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [138]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

row_idx 0 row [1 2]
col_idx 0 element 1
col_idx 1 element 2
row_idx 1 row [3 4]
col_idx 0 element 3
col_idx 1 element 4


In [139]:
# each element in M is now squared
M

array([[ 1,  4],
       [ 9, 16]])

## Further reading

* http://numpy.scipy.org
* http://scipy.org/Tentative_NumPy_Tutorial